#!/bin/bash

set -Eeuo pipefail

workdir='/app'

PS3='Please select a container: '
IFS=$'\n' read -r -d '' -a docker_containers < <((docker ps --format='{{ .Names }}' | sort -V) && printf '\0')

if [ -z "${docker_containers+x}" ]; then
  echo 'No running containers found'
  exit 1
fi

executable_exists() {
  which "$1" >/dev/null 2>&1
}

if executable_exists "code" && executable_exists "cursor"; then
  echo "Please select an IDE to launch:"
  echo "1) Code"
  echo "2) Cursor"
  read -r choice
  case $choice in
    1) selected_editor="code" ;;
    2) selected_editor="cursor" ;;
    *) echo "Invalid selection." ;;
  esac
elif executable_exists "code"; then
  selected_editor="code"
elif executable_exists "cursor"; then
  selected_editor="cursor"
else
  echo "Warning: Neither 'code' nor 'cursor' executable found."
  exit 1
fi

echo "Selected editor: '$selected_editor'"

echo "Running containers:"
select container_name in "${docker_containers[@]}"; do
  text="{\"containerName\":\"/${container_name}\"}"
  hex_container_name=$(printf $text | od -A n -t x1 | tr -d '[\n\t]' | tr -d '[:space:]' | tr -d ' ')

  echo 'Starting the editor'
  $selected_editor --folder-uri="vscode-remote://attached-container+${hex_container_name}${workdir}"
  break
done
